version: '2.2'

services: 
    phpfpm: 
        image: phpdockerio/php73-fpm
        working_dir: /src
        volumes:
            - ${DIRECTORY}:/src
        command: /bin/bash -c "apt-get update && apt-get install -y php-ds php-mbstring \
                 && /usr/sbin/php-fpm7.3 -O"