<?php

namespace Patterns;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-07-31 at 07:55:52.
 */
class PrototypeTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Prototype
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
       // $this->object = new Prototype;
       $obj = new Proto();
       $obj->getting(56);
       $this->assertInstanceOf(Prototype::class, $obj);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {

    }

    public function test()
    {
        $this->assertTrue(true);    
    }
}
