name: Algorithms-Ds
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        extensions: ds, psr, mbstring
        php-version: "7.3"
    - name: Run test suite
      run: php validate.php
